services:
  analyticsdocs:
    image: analyticsdocs
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    volumes:
      - /Users/afurze/Projects/analytics_docs/:/output

volumes:
  output: